sudo: required
os: linux
language: minimal
addons:
  apt:
    packages:
    - docker-ce
git:
  depth: 4
services:
  - docker

before_install:
  - docker pull debian:stretch-slim

script:
  - docker version
  - docker build --no-cache --tag lltest/gamesvr-ut2004 --tag lacledeslan/gamesvr-ut2004 --build-arg BUILDNODE=TravisCI --build-arg SOURCE_COMMIT="$TRAVIS_COMMIT" ./linux

notifications:
  slack:
    secure: ezOkZKUQoyV0LUEmqRj/lpKBK9hqJlPHhMizwBNulm7hGpxuWLTHXZhJHCW7tTYE+XwhzlzMdU/+L89rhLCK3ediz6a6hUI0eYaacN63oixAt1WZ26RnbzxcIzYreXRN3SSaiKl+fQD7g6guXUuR5l81MSyVq579nUyuydZb3Qfp6zNAh+J2lSFDLfFVGu3Tzo+cmPAzHe5Sj23Zeu8TNAn3QhcBE3PKGtF6vmD9lRcFwMCShZ4/wlUt5aIBsSTAlMpD4gdTk20/9F/aq9iuOGGfcJ0vy1FzkGmBIHJML2mpPVQwe5vhj4sMoHxoB8SW1F/X/T1t4peuvYj7yKBAfHONWAzIHnWRHMx7BPKhmS0RPKkck2gtD94sui/vvuulEUMtWD221t6sQWhfzCG88YvltoBF7bSjb9N9RVO2RA/+T+PN7dXjrPfEQf2wKJNTQCJ66JBBd4j//kR87RHM+oeK8JXmB+ozSHAWuI/XgWQWvxdg2bqRXJqyIGvvNRrHnQkKw+NzyT3t3cP/rcMFIu9UkSlxPBex4IiE5WRqfqsDYg0FvnESVs2Yq8WyiWn+Ehlr0tlOAJlngLzB+YSlCARcfZ8AfepT4u9jRpZOp+HPb8y6Iutr529b9wcSkCHjCdtbA911EXmraa/3hUpwcoPLspgCLSWrgCMCEA+A6Iw=

before_deploy:
  - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASS";
deploy:
  provider: script
  script: docker push lacledeslan/gamesvr-ut2004
  on:
    branch: master
after_deploy:
  - curl -X POST https://hooks.microbadger.com/images/lacledeslan/gamesvr-ut2004/$MICROBADGER_TOKEN
